# .streamlit/secrets.toml

[credentials.admin]
name = "Admin"
password = '$2b$12$GsKEDdZrfKdXXewchFgGdu8Ky0H3.UPtmfbArzGZseKAhdXG/LRgK'

[credentials.dyan]
name = "Dyan"
password = '$2b$12$GsKEDdZrfKdXXewchFgGdu8Ky0H3.UPtmfbArzGZseKAhdXG/LRgK'